services:
  pgdb:
    image: postgres
    restart: always
    volumes:
      - db-volume-pg-ol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pgol
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
    networks:
      - arch-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pguser"]
      interval: 5s
      timeout: 1s
      retries: 5

  parser:
    image: parser
    volumes:
      - ./cfg:/app/cfg
      - ./data:/app/data
    networks:
      - arch-network
    depends_on:
      pgdb:
        condition: service_healthy

volumes:
  db-volume-pg-ol:


networks:
  arch-network:
    driver: "bridge"
    external: false
